# docker-compose.yml
version: '3.8'

services:
  base:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: cosyvoice-base:latest
    profiles: ["base"]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - cosyvoice_cache:/root/.cache/modelscope
      - cosyvoice_output:/app/static
    restart: unless-stopped
    depends_on:
      - base

  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    ports:
      - "7870:7860"
    volumes:
      - cosyvoice_cache:/root/.cache/modelscope
    depends_on:
      - base
#    restart: unless-stopped

volumes:
  cosyvoice_cache:
  cosyvoice_output: