# docker-compose.yml
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./pretrained_models:/cosyvoice_src/pretrained_models
      - cosyvoice_cache:/root/.cache/modelscope
      - cosyvoice_output:/app/static
    restart: unless-stopped

  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    ports:
      - "7870:7860"
    volumes:
      - ./pretrained_models:/cosyvoice_src/pretrained_models
      - cosyvoice_cache:/root/.cache/modelscope
    restart: unless-stopped

volumes:
  cosyvoice_cache:
  cosyvoice_output: