# web/environment-cpu.yml 或 gradio/environment-cpu.yml
name: cosyvoice-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  # Python 基础
  - python=3.10
  - pip

  # CosyVoice 依赖（conda 中有且版本兼容的）
  - numpy=1.26.4
  - librosa=0.10.2
  - pydub=0.25.1
  - onnx=1.16.0
  - onnxruntime=1.18.0
  - pyworld=0.3.4
  - inflect=7.3.1
  - rich=13.7.1
  - protobuf=4.25
  - pyarrow=18.1.0
  - pydantic=2.7.0
  - omegaconf=2.3.0
  - hydra-core=1.3.2
  - networkx=3.1
  - diffusers=0.29.0
  - transformers=4.51.3
  - tensorboard=2.14.0
  - gdown=5.1.0

  # 通过 pip 安装的包（conda 中版本不匹配或不存在）
  - pip:
      # 这些包在 conda 中版本不匹配，改用 pip
      - gradio==5.4.0
      - matplotlib==3.7.5
      - modelscope==1.20.0
      - soundfile==0.12.1
      - wget==3.2
      # 其他包
      - conformer==0.3.2
      - HyperPyYAML==1.2.2
      - openai-whisper==20231117
      - wetext==0.0.4
      - matcha-tts
      # PyTorch CPU 版本
      - torch==2.3.1+cpu
      - torchaudio==2.3.1+cpu
      - --extra-index-url https://download.pytorch.org/whl/cpu